### ISSUE TITLE
Adding Massachusetts State House District data 

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/ECHO-Geo#1]
geoJSON in WGS84 of the Massachusetts State House District Data - 

[Massachusetts_House_Legislative_Districts.geojson.zip](https://github.com/edgi-govdata-archiving/ECHO-Geo/files/4827987/Massachusetts_House_Legislative_Districts.geojson.zip)

**Comment by mraisle** [comment]
@ericnost here's the house district data!

**Comment by mraisle** [comment]
I've only previewed this in R so let me know if there are any problems!

**Comment by mraisle** [comment]
Original data source - https://hub.arcgis.com/datasets/2090314937f74285bd883413dd880d0e_0/data?geometry=-74.530%2C41.507%2C-68.779%2C42.931

**Comment by ericnost** [comment]
Thank you @mraisle!!! I've now added you to this repo, with write permissions. I'd encourage you to give it a shot, adding the file directly to the repo.
